package org.lld.parking_lot.models;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class Ticket extends BaseModel {
    private String number;
    private Date entryTime;
    private ParkingSpot parkingSpot;
    private Vehicle vehicle;
    private Gate generatedAt;
    // not so useful
    private Operator generatedBy;

    @Override
    public String toString() {
        return "\n" +
                "Parking At: " + this.getGeneratedAt().getParkingLot().getName() + "\n" +
                "Ticket Number: " + number  + "\n" +
                "Entry Time: " + entryTime + "\n" +
                "Parking Spot: " + parkingSpot + "\n" +
                "Vehicle Number: " + vehicle + "\n" +
                "Vehicle Type: " + vehicle.getType() + "\n" +
                "Owner Name: " + vehicle.getOwnerName() + "\n" +
                "Generated At Gate: " + generatedAt + "\n" +
                "Generated By: " + generatedBy;
    }
}
